### ISSUE TITLE
Adicionar exemplo de como integrar o Keycloak como Identity Broker e o Gov.br como Identity Provider

### ISSUE THREAD

**Issue by piantino** [servicosgovbr/manual-roteiro-integracao-login-unico#25]
Olá,

Gostaria de compartilhar a configuração que fiz para o **Keycloak** usar o Gov.br como **Identity provider,** ou seja, como adicionar um botão no Keycloak para o usuário se logar com o Gov.br.

![image](https://user-images.githubusercontent.com/737364/205133493-48ccf5b0-ffea-40a5-ac57-99fdbf6e20c8.png)

A configuração utilizada:
![image](https://user-images.githubusercontent.com/737364/205133589-d2c17b52-5376-4bd2-9073-1ade64144e65.png)

Acredito que seria interessante colocar no exemplo de implementação, mas apenas ficando registrado aqui já pode ajudar alguém.

**Comment by rdurelli** [comment]
Alguem testou isso? Deu certo?

**Comment by weltonrodrigo** [comment]
Eu uso faz um tempo e é basicamente isso, com algumas alterações, só:
- validação de assinaturas: a solução do gov.br atual interpreta errado o RFC e o formato do jwks não é reconhecido pelo keycloak. Dessa forma, precisa fazer validação manual, extraindo a chave em https://sso.acesso.gov.br/jwk e colocando no campo validar assinatura (precisa estar atento porque quando a chave for rotacionada o login vai parar de funcionar)
- A url de user info é https://sso.acesso.gov.br/userinfo
- o Default Scopes é "openid email profile govbr_confiabilidades" (embora esse escopo parece não ser mais utilizado, é o que tá na documentação).
- O accept prompt=none pode estar ON, e é importante que esteja, para permitir checagem do SSO ao abrir o app (mas a técnica de checagem via iframe é bloqueada no gov.br)

## É importante notar que:

1. Para obter foto do usuário, níveis da conta (bronze, prata, ouro) e selos de confiabilidade (diversos), é preciso utilizar o token gov.br original, pra isso, é preciso ativar as opções `Store token` e `Stored tokens readable` para que o app possa obter o token gov.br original e chamar o endpoint apropriado. A obtenção do token é feita como descrito no doc https://www.keycloak.org/docs/latest/server_admin/#retrieving-external-idp-tokens:
```
# para o nome de provider (gov.br) e realm (dev) usados na imagem :
GET /realms/dev/broker/gov.br/token HTTP/1.1
Host: localhost:8080
Authorization: Bearer <KEYCLOAK ACCESS TOKEN>
```
A resposta é o token original gov.br que a aplicação pode usar pra chamar os endpoints.

2. Talvez antigamente as confiabilidades e nível da conta viessem dentro do token (daí a existência do escopo), mas atualmente não vem mais e é preciso essa chamada subsequente. É importante que o dev compreenda que é necessário fazer essa checagem do nível da conta e confiabilidade no backend e não confie numa checagem feita no frontend.
Isso é importante porque embora o frontend possa ser mexido pelo usuário, quando ele submete o token no backend para chamar uma api do app, como o token tem uma garantia criptográfica de que está correto (e pode ser checado), o backend pode confiar que se o token é válido, as informações ali dentro também são. Mas como a informação de nível de conta e confiabilidade não está _DENTRO_ do token, precisaria ser passada por fora e por isso está sujeita a ser forjada.
Dessa forma, a aplicação precisa ou checar o nível de confiabilidade toda vez  (com um cache adequado) que os seus endpoints próprios sejam chamados, ou precisa considerar o usuário logado e autorizado apenas depois da checagem ocorrer no backend e aí emitir seu mecanismo próprio de controle de sessão (cookies ou um token JWT próprio).

3. É uma pena também que a solução atual não consiga fazer o set-up authentication (ver https://github.com/servicosgovbr/manual-roteiro-integracao-login-unico/issues/23) porque o Keycloak atualmente suporta e seria transparente passar a exigir segundo fator (ou múltiplos fatores) de autenticação para algumas operações.

Eu venho usando o keycloak como intermediário entre o órgão e o gov.br há anos com essas configurações e funciona muito bem, mas com essas ressalvas.

**Comment by rdurelli** [comment]
Basicamente vc deu uma aula :) irei teste. Qualquer coisa lhe peço ajuda. Muito obrigado

**Comment by piantino** [comment]
Perfeito as explicações @weltonrodrigo,

Sobre o scope "govbr_confiabilidades" é necessário para permitir que o token retornado pelo Gov.br tenha permissão de chamar os serviços de confiabilidade, do contrário retornará um erro assim:

```
{
  "errors": [
    {
      "status":401,
      "code":"ACCESSTOKEN_SCOPE_MUSTCONTAINSEXPECTEDSCOPE",
      "title":"Escopo requerido não encontrado. Valor esperado: '{0}', valor recebido: '{1}'." 
    }
  ]
}
```
Pelo menos foi o que aconteceu nos meus testes.

**Comment by caduvieira** [comment]
> @rdurelli é basicamente isso, eu sugeriria apenas algumas alterações:
> 
> * validação de assinaturas: a solução do gov.br atual interpreta errado o RFC e o formato do jwks não é reconhecido pelo keycloak. Dessa forma, precisa fazer validação manual, extraindo a chave (campo `n`) em https://sso.acesso.gov.br/jwk e colocando no campo validar assinatura (precisa estar atento porque quando a chave for rotacionada o login vai parar de funcionar)

Em que ponto o Login gov.br interpreta a RFC 7517 errada ? O exemplo no https://www.rfc-editor.org/rfc/rfc7517#appendix-A tem os mesmos campos retornados pelo https://sso.acesso.gov.br/jwk. Há algum problema com os valores?

**Comment by weltonrodrigo** [comment]
> Em que ponto o Login gov.br interpreta a RFC 7517 errada ? O exemplo no https://www.rfc-editor.org/rfc/rfc7517#appendix-A tem os mesmos campos retornados pelo https://sso.acesso.gov.br/jwk. Há algum problema com os valores?

Você tem razão que o RFC coloca o campo 'use' como OPTIONAL. É mais correto eu dizer que o gov.br e o keycloak _discordam_ sobre o formato do jwk.

No teste que realizei pra fazer esse comentário o pyjwt conseguiu validar corretamente a partir da url do keyset e quando eu criei [esse repo](https://github.com/weltonrodrigo/govbr_test/blob/88652ae6ba9c20cd91fec29b74f3847fde1fdb1d/token_request.py#L49), isso não acontecia, tinha que fornecer a chave manualmente. Suponho então que o pyjwt tenha se alinhado.

**Comment by acostaaluiz** [comment]
Quando adiciono um novo identity provider no keycloak, ele coloca um valor default no campo redirect uri. Eu não consigo edita-lo e para colocar o valor https://sso.tjsc..... conforme mostra no print. Alguma dica? Valeu

**Comment by piantino** [comment]
> Quando adiciono um novo identity provider no keycloak, ele coloca um valor default no campo redirect uri. Eu não consigo edita-lo e para colocar o valor https://sso.tjsc..... conforme mostra no print. Alguma dica? Valeu

O Redirect URI é a URL do seu Keycloak (no print é o Keycloak do TJSC) e não pode ser alterado, já o Authorization URL é a do Gov.br.
Pensa que o seu keycloak é o cliente do SSO do Gov.br, e outras aplicações serão os clientes do seu keycloak.
Ficou mais claro agora?

**Comment by rpfcool** [comment]
Prezados,

Agradeço profundamente pelo valioso conteúdo disponibilizado, o qual tem sido de grande auxílio.

Gostaria de indagar se alguém possui conhecimento sobre o procedimento para recuperar o CPF do usuário no Keycloak.

**Comment by carlosrodovalho** [comment]
estou tantando fazer a implementação do gov.br em um servidor de homologação da minha instituição, no entanto após informar o CPF e senha na tela de login do Gov.br, o usuário é retornado pra aplicação e o keycloak exibe a mensagem:

```
Unexpected error when authenticating with identity provider
« Back to Application
```

no log do keycloak aparece esse erro:

```
2024-08-05 17:10:16,864 WARN  [org.keycloak.events] (executor-thread-173) type="IDENTITY_PROVIDER_LOGIN_ERROR", realmId="35-secret-e072bb", realmName="virtualif-homologacao", clientId="virtualif-modulo-copese", userId="null", ipAddress="192.168.1.254", error="identity_provider_login_failure", code_id="8158e5-secret-29abf3bc"
2024-08-05 18:19:51,484 WARN  [org.keycloak.keys.infinispan.InfinispanPublicKeyStorageProvider] (executor-thread-187) PublicKey wasn't found in the storage. Requested kid: 'rsa1' . Available kids: '[]'
2024-08-05 18:19:51,486 ERROR [org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider] (executor-thread-187) Failed to make identity provider oauth callback: org.keycloak.broker.provider.IdentityBrokerException: token signature validation failed
        at org.keycloak.broker.oidc.OIDCIdentityProvider.parseTokenInput(OIDCIdentityProvider.java:679)
        at org.keycloak.broker.oidc.OIDCIdentityProvider.validateToken(OIDCIdentityProvider.java:696)
        at org.keycloak.broker.oidc.OIDCIdentityProvider.validateToken(OIDCIdentityProvider.java:690)
        at org.keycloak.broker.oidc.OIDCIdentityProvider.getFederatedIdentity(OIDCIdentityProvider.java:379)
        at org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider$Endpoint.authResponse(AbstractOAuth2IdentityProvider.java:557)
        at org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider$Endpoint$quarkusrestinvoker$authResponse_ab908fbdd086ee82e140d8a818c077362a2d04b4.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

alguém tem alguma ideia do que pode ser? desde já agradeço

**Comment by weltonrodrigo** [comment]
> estou tantando fazer a implementação do gov.br em um servidor de homologação da minha instituição, no entanto após informar o CPF e senha na tela de login do Gov.br, o usuário é retornado pra aplicação e o keycloak exibe a mensagem:
> 
> ```
> Unexpected error when authenticating with identity provider
> « Back to Application
> ```
> 
> no log do keycloak aparece esse erro:
> 
> ```
> 2024-08-05 17:10:16,864 WARN  [org.keycloak.events] (executor-thread-173) type="IDENTITY_PROVIDER_LOGIN_ERROR", realmId="35-secret-e072bb", realmName="virtualif-homologacao", clientId="virtualif-modulo-copese", userId="null", ipAddress="192.168.1.254", error="identity_provider_login_failure", code_id="8158e5-secret-29abf3bc"
> 2024-08-05 18:19:51,484 WARN  [org.keycloak.keys.infinispan.InfinispanPublicKeyStorageProvider] (executor-thread-187) PublicKey wasn't found in the storage. Requested kid: 'rsa1' . Available kids: '[]'
> 2024-08-05 18:19:51,486 ERROR [org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider] (executor-thread-187) Failed to make identity provider oauth callback: org.keycloak.broker.provider.IdentityBrokerException: token signature validation failed
>         at org.keycloak.broker.oidc.OIDCIdentityProvider.parseTokenInput(OIDCIdentityProvider.java:679)
>         at org.keycloak.broker.oidc.OIDCIdentityProvider.validateToken(OIDCIdentityProvider.java:696)
>         at org.keycloak.broker.oidc.OIDCIdentityProvider.validateToken(OIDCIdentityProvider.java:690)
>         at org.keycloak.broker.oidc.OIDCIdentityProvider.getFederatedIdentity(OIDCIdentityProvider.java:379)
>         at org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider$Endpoint.authResponse(AbstractOAuth2IdentityProvider.java:557)
>         at org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider$Endpoint$quarkusrestinvoker$authResponse_ab908fbdd086ee82e140d8a818c077362a2d04b4.invoke(Unknown Source)
>         at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
>         at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
>         at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
>         at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
>         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
>         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
>         at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
>         at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
>         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
>         at java.base/java.lang.Thread.run(Thread.java:1583)
> ```
> 
> alguém tem alguma ideia do que pode ser? desde já agradeço

Experimenta desativar a opção “validate signature”.

**Comment by caduvieira** [comment]
Isso está relacionado a issue #29.

> > Experimenta desativar a opção “validate signature”.
> 
> Muito obrigado @weltonrodrigo . Desativando a checagem pelo JWKS o login funciona perfeitamente. No entanto ao fazer isso eu não estaria diminuindo a segurança do processo de login? Existe alguma maneira de realizar a integração mantendo a checagem da assinatura e tmb usando PKCE? Mais uma vez obrigado pela ajuda

**Comment by carlosrodovalho** [comment]
> 
> Sim. Estaria.

Entendi. Obrigado.

Caso eu crie um endopoint próprio, que leia o objeto retornado por https://sso.acesso.gov.br/jwk, adicione a ele o campo `use: sig`, e responda a requisição com objeto "completo", conforme o keycloak espera. E então configurar esse endpoint como 'JWKS URL' no keycloak. 

Em teoria, com essa estratégia eu poderia realizar a assinatura, correto?

E imagino que nesse cenário não seria possível ativar a opção 'Use PKCE', certo?

**Comment by weltonrodrigo** [comment]
> > Experimenta desativar a opção “validate signature”.
> 
> Muito obrigado @weltonrodrigo . Desativando a checagem pelo JWKS o login funciona perfeitamente. No entanto ao fazer isso eu não estaria diminuindo a segurança do processo de login? Existe alguma maneira de realizar a integração mantendo a checagem da assinatura e tmb usando PKCE? Mais uma vez obrigado pela ajuda

Sim, diminui. Mas não é teu grave pq tá num ambiente controlado e você recebe o token gov.br a partir de um request que você mesmo faz ao endpoint de token do Gov.br. Nao é algo que você recebe dos clientes e precisa validar. 

O PKCE é independente e não relacionado. Você pode ativar ele mesmo sem validar assinaturas do token.

**Comment by rosendoalex** [comment]
Bom dia!

Estou fazendo a integração entre o Keycloak e o Gov.br, está funcionando, porém consigo realizar o logout do Gov.br, mas o Keycloak ainda permanece logado. Alguém já viu esse caso?

Fiz as configurações de logout URL que o passo a passo do Gov.br forneceu.

**Comment by weltonrodrigo** [comment]
> Estou fazendo a integração entre o Keycloak e o Gov.br, está funcionando, porém consigo realizar o logout do Gov.br, mas o Keycloak ainda permanece logado. Alguém já viu esse caso?

Entendi que você fez logout direto no gov.br, sem envolver a aplicação que está falando com o keycloak. Correto?

Salvo melhor juízo, o gov.br não implementa o logout centralizado. Isto é, se você logar com gov.br numa aplicação via keycloak e depois numa outra ata do mesmo browser você acessar acesso.gov.br e fizer logout por lá (note que o acesso.gov.br é uma aplicação que não tem nenhuma ligação com o seu keycloak, só com o gov.br), o keycloak não vai saber que você deslogou do gov.br.

Isso é o chamado RP-Initiated logout (o Relaying Party no caso aí é o acesso.gov.br) e o gov.br enquanto Identity Provider deveria implementar ou o [Front-channel logout](https://openid.net/specs/openid-connect-frontchannel-1_0.html)  ou o [Backchannel logout](https://openid.net/specs/openid-connect-backchannel-1_0.html).

Em outras palavras, o gov.br é que é responsável para avisar a sua aplicação (ou o seu keycloak, no caso) que foi feito um logout no gov.br em outra janela, iniciado por outra aplicação. Até onde eu sei ele não faz isso, mas seria ótimo que eu estivesse errado e só minha configuração que foi mal feita.

O workaround nesse caso é você limitar o tempo máximo de sessão do seu keycloak para 59 minutos (pra ser menor que o do gov.br) e configurar sua aplicação para ter uma expiração adequada do token de acesso (e usar refresh tokens). Assim, o seu usuário vai ficar no máximo 59 minutos + <validade do token de acesso> logado no seu keycloak depois de ter feito logout no gov.br em outro lugar.

**Comment by rosendoalex** [comment]
Olá @weltonrodrigo!

Perfeita sua explicação, muito obrigado!

**Comment by danieljuliao** [comment]
Caros,

Sobre executar logout numa aplicação cuja autenticação foi realizada via gov.br, em outra aplicação do mesmo reino do keycloak também é possível observar que o logout também acontece. Acredito que a habilitação do Backchannel logout seja importante nesse quesito.

Aqui o problema é justamente no logon. Quando executamos logon via gov.br numa aplicação, esse logon não se replete em outra aplicação do emsmo reino do Keycloak, ela pede autenticação, é como se o SSO não estivesse funcionando. Alguém passou por problema similar?

**Comment by piantino** [comment]
> Caros,
> 
> Sobre executar logout numa aplicação cuja autenticação foi realizada via gov.br, em outra aplicação do mesmo reino do keycloak também é possível observar que o logout também acontece. Acredito que a habilitação do Backchannel logout seja importante nesse quesito.
> 
> Aqui o problema é justamente no logon. Quando executamos logon via gov.br numa aplicação, esse logon não se replete em outra aplicação do emsmo reino do Keycloak, ela pede autenticação, é como se o SSO não estivesse funcionando. Alguém passou por problema similar?

Olá @danieljuliao,

Confirma se após o primeiro login com gov.br nos dados do usuário aparece na aba "Identity Provider Links" o vínculo com o IDP gov.br que criou.
Se não vinculou verifica o fluxo de "First Broken Login" que o IDP está usando.
Esse fluxo depende muito da forma como está estruturado a gestão de usuários do seu keycloak.

**Comment by weltonrodrigo** [comment]
> Caros,
> 
> Sobre executar logout numa aplicação cuja autenticação foi realizada via gov.br, em outra aplicação do mesmo reino do keycloak também é possível observar que o logout também acontece. Acredito que a habilitação do Backchannel logout seja importante nesse quesito.

A terminologia é confusa aqui, mas o keycloak suporta tanto backchannel quando frontchannel logout (mas isso é entre o keycloak e as tuas aplicações. O fato do keycloak ter um identity provider upstream é um detalhe que as tuas aplicações não ficam nem sabendo.

O gov.br, no entanto, não suporta nem backchannel nem frontchannel logout. Isto é, ele não implementa nem um jeito de avisar _outras_ aplicações de que o usuário deslogou. O que ele implementa é só um jeito de uma aplicação específica deslogar o usuário, é o chamado RP-Initiated Logout no parlance do OpenID. O usuário desloga do gov.br da aplicação A, mas a B não fica nem sabendo.

Se o usuário faz logout em A: 
- Se A e B estiverem no keycloak, tudo certo.
- Se A estiver no keycloak e B for o scdp.gov.br por exemplo, o scdp não vai saber que o usuário deslogou. Nem vice-versa.

> Aqui o problema é justamente no logon. Quando executamos logon via gov.br numa aplicação, esse logon não se replete em outra aplicação do emsmo reino do Keycloak, ela pede autenticação, é como se o SSO não estivesse funcionando. Alguém passou por problema similar?

Eu começaria desabilitando o gov.br nesse realm e criando um usuário de teste local. Se o comportamento se repetir, o problema é na conf de autenticação do keycloak ou na configuração da aplicação.

Coisas pra checar:
- O fluxo de autenticação foi mexido? Se sim, o login via cookie está foi desabilitado? É ele que faz o usuário ser "lembrado". Só vai pro login se o cookie não existir ou estiver expirado, por padrão. Mas é possível alterar isso e pedir login toda hora.
- A aplicação está incluindo `prompt=login` na url de autenticação? é a que se parece com `https://meukecloak.com.br/realms/meurealm/protocol/openid-connect/auth?client_id=oidcdebugger&redirect_uri=https%3A%2F%2Foidcdebugger.com%2Fdebug&scope=openid&response_type=code%20token&response_mode=form_post&state=cpnckxbft6v&nonce=yqdnbbyawe`. `Prompt=login` força login novamente.
- Checar se as duas aplicações realmente estão logando no mesmo realm. Você pode checar essa mesma url pra ver se estão no mesmo realm (ela aparece no formulário de login do keycloak, ou no console do browser).

**Comment by danieljuliao** [comment]
> Confirma se após o primeiro login com gov.br nos dados do usuário aparece na aba "Identity Provider Links" o vínculo com o IDP gov.br que criou.
> Se não vinculou verifica o fluxo de "First Broken Login" que o IDP está usando.
> Esse fluxo depende muito da forma como está estruturado a gestão de usuários do seu keycloak.

@piantino,

Tá tudo certo com o link, se o usuário do keycloak existir ele insere o link. Se o usuário dp Keycloak não existir, nos criamos tal usuário com todas as informações possíveis advindas do gov.br, e inserimos o link também.

**Comment by weltonrodrigo** [comment]
@danieljuliao 

> Acredito que para o Keycloak, esses identities providers não tem a confibilidade necessária, então por default o logon executado via algum desses identities providers não é pássível do SSO, obrigando sempre a solicitação de login, mesmo as aplicações estando no mesmo reino. Vou ter que pesquisar mais um pouco, pois no caso do gov.br, teremos que ter o SSO funcionando por se tratar de aplicações governamentais.

O login com identity provider no keycloak é pra funcionar normalmente, é pra ter o mesmo efeito como se o usuário tivesse colocado usuário e senha.

A gente utiliza aqui normalmente login via identity provider (com o gov.br) com SSO entre várias aplicações.

> Quando usamos a autenticação pelas vias normais dos usuários do keycloak cadastrados, inclusive os advindos do gov.br, caso no futuro seja inserido alguma credencial pra eles, tudo dá certo e o SSO funciona como deveria, a autenticação está padrão, e há verificação, não existindo a necessidade de pedir login novamente. As aplicações estão no mesmo reino e sem o 'Prompt=login'.

Pelo que entendi então se o usuário faz login com usuário e senha o SSO entre as aplicações está ok, só quando o usuário loga usando o o gov.br na aplicação A, quando vai na aplicação B ele tem que logar novamente.

Eu fiquei perdido aí. Na minha experiência o Keycloak funciona normal nesse setup, de modos que eu tendo a achar que a dificuldade então estaria entre a tua aplicação e o Keycloak.

Eu checaria, usando o console do browser, para a segunda tentativa de login (aplicação B):
- Como está a url de autenticação que a tua aplicação está montando e usando para redirecionar o browser do usuário para iniciar o login?
- Quando o browser então faz o request de GET para essa URL, ele tá mandando corretamente os cookies? Os que eu esperaria ver são assim:
![Image](https://github.com/user-attachments/assets/98aaf51c-fa47-44a9-b469-24fbc37138be)


Agora, me ocorreu o seguinte, quando você fala em "SSO", você tá falando de qual comportamento?

**Comportamento 1:**
1. usuário entra na aplicação A, vai pra tela de login da aplicação A, faz o fluxo de auth do keycloak (inclusive logando no gov.br), retorna para aplicação A logado;
2. usuário entra na aplicação B, vai pra tela de login da aplicação B, passa pela fluxo de auth do keycloak (sem precisar reautenticar, porque já está com sessão ativa no keycloak) e retorna para aplicação B logado;
**Comportametno 2:**
1. usuário entra na aplicação A, vai pra tela de login da aplicação A, faz o fluxo de auth do keycloak (inclusive logando no gov.br), retorna para aplicação A logado;
2. usuário entra na aplicação B, aplicação já reconhece que o usuário tem sessão ativa no keycloak via iframe, usuário entra na aplicação B logado;

Para o caso do comportamento 2, vale a pena você olhar as diretivas de Content-Security-Policy para o realm, se estão no default. No entanto, como você falou que sem o gov.br funciona, estou perdido.

**Comment by carlosrodovalho** [comment]
Para quem estiver com o mesmo problema, a solução é atualizar o Keycloak para 26.4, como indicado na issue #43 . Obrigado ao @ervison pela contribuição.

**Comment by danieljuliao** [comment]
> Eu fiz testes desse fluxo no ambiente de staging do Gov.br, e lá o comportamente esperado acontece. Ao fazer logou nas minhas aplicações, a sessão no Gov.br (staging) é encerrada. As minhas configurações do identity provider no keycloak de homologação e produção estão idênticas, mas o logout não acontece no ambiente de produção.
> 
> Inclusive encontrei um relato similar: [#24](https://github.com/servicosgovbr/manual-roteiro-integracao-login-unico/issues/24)

@carlosrodovalho, talvez seja a configuração do client do Keycloak lá do gov.br que esteja diferente, a de produção, no caso. a backchannel logout URL não deve estar configurada. Teria que colocar a URL no formato abaixo no client de prod.

https://seudominio/auth/realms/{realm-name}/protocol/openid-connect/logout/backchannel-logout

**Comment by leonardoapretti** [comment]
Boa tarde, pessoal!

Estou tentando realizar o logout no keycloak e Govbr a partir da minha aplicaçãp next, contudo, estamos sendo redirecionados para a url https://sso.staging.acesso.gov.br/login?client_id=h-portal-logado.estaleiro.serpro.gov.br&authorization_id=..... e não volta para a aplicação.

Tentei implementar o fluxo descrito em acima, contudo, não está funcionando. Vou mandar as configurações que fiz aqui para ajudar no entendimento:

// apps/zz/auth/next/get-logout-url.ts
`
'use server';

import { getAuthToken } from './utils';

export async function getLogoutUrl(): Promise<string> {
  const issuer = process.env.KEYCLOAK_ISSUER;
  const appUrl = process.env.NEXTAUTH_URL;

  if (!(issuer && appUrl)) {
    throw new Error('[getLogoutUrl] KEYCLOAK_ISSUER ou NEXTAUTH_URL ausentes');
  }

  const token = await getAuthToken();

  const logoutUrl = new URL(`${issuer}/protocol/openid-connect/logout`);

  if (token?.idToken) {
    logoutUrl.searchParams.set('id_token_hint', token.idToken as string);
  }

  // encadeia o redirect para o GovBR /logout.
  logoutUrl.searchParams.set(
    'post_logout_redirect_uri',
    appUrl // URL da aplicação
  );

  return logoutUrl.toString();
}
`

// apps/zz/components/ui/sign-out-button.tsx
`
'use client';

import { getLogoutUrl } from '@/auth/next/get-logout-url';
import logger from '@/lib/pino/logger';
import {
  Button,
  type ButtonProps,
} from '@repo/design-system/components/ui/button';
import { LogOut } from 'lucide-react';
import { signOut } from 'next-auth/react';
import { useState } from 'react';

interface SignOutButtonProps
  extends Pick<ButtonProps, 'className' | 'variant' | 'size'> {
  /** Texto do botão. Default: "Sair" */
  label?: string;
  /** Texto exibido durante o logout. Default: "Saindo..." */
  loadingText?: string;
}

export function SignOutButton({
  label = 'Sair',
  loadingText = 'Saindo...',
  className,
  variant = 'outline',
  size = 'sm',
}: SignOutButtonProps) {
  const [isLoading, setIsLoading] = useState(false);

  async function handleSignOut() {
    if (isLoading) {
      return;
    }
    setIsLoading(true);

    try {
      // Passo 1: Obtém a URL de logout via Server Action.
      // Feito ANTES do signOut para garantir que a sessão ainda existe
      // quando getAuthToken() for chamado na action.
      const url = await getLogoutUrl();

      // Passo 2: Invalida a sessão Next.js sem redirecionar.
      await signOut({ redirect: false });

      // Passo 3: Redireciona o browser para o Keycloak, que encadeia
      // para o GovBR via front-channel, destruindo o cookie de sessão
      // do GovBR antes de devolver o browser para a aplicação.
      window.location.href = url;

    } catch (error) {
      logger.error(error, '[SignOutButton] Erro durante logout');
      await signOut({ callbackUrl: '/' });

    } finally {
      setIsLoading(false);
    }
  }

  return (
    <Button
      className={className}
      disabled={isLoading}
      loading={isLoading}
      loadingText={loadingText}
      onClick={handleSignOut}
      size={size}
      variant={variant}
    >
      <LogOut />
      {label}
    </Button>
  );
}
`

Configuração do Client Keycloak
Valid redirect URIs:
https://zz.dev.uks.ufes.br/*

Valid post logout redirect URIs:
https://zz.dev.uks.ufes.br/*

Backchannel logout desabilitado

Alguma dessas configurações está errada? Também cadastrei a Url de Logout no Govbr, conforme indicação acima: 
https://meudominio.gov.br/auth/realms/<realm_name>/broker/<nome_do_identity_provider>/endpoint/logout_response

**Comment by weltonrodrigo** [comment]
@leonardoapretti eu entendi que do lado da tua aplicação tá tudo certo. Mas das duas, uma:
- o comportamento do gov.br de homologação mudou e o redirecionamento não tá funcionando
- o cadastro da tua url de `post_logout_redirect_uri` no gov.br não tá correto.

Você falou que já fez esse cadastro lá corretamente da url `https://meudominio.gov.br/auth/realms/<realm_name>/broker/<nome_do_identity_provider>/endpoint/logout_response` no gov.br, mas eu diria que vale a pena checar.

**Comment by leonardoapretti** [comment]
Boa tarde!

Passando apenas para dar um feedback. O fluxo estava correto mesmo e o problema era um espaço a mais na url de logout cadastrada no govbr. 

Valeu pela ajuda, pessoal!
